
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue May 03 13:57:37 BRT 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "dividir", namespace = "http://default_package/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dividir", namespace = "http://default_package/", propOrder = {"arg0", "arg1"})

public class Dividir {

    @XmlElement(name = "arg0")
    private java.lang.Integer arg0;
    @XmlElement(name = "arg1")
    private java.lang.Integer arg1;

    public java.lang.Integer getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Integer newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.Integer getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.Integer newArg1)  {
        this.arg1 = newArg1;
    }

}

